apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service
  labels:
    app: info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
        - name: info-service
          image: biquyt/info-service:1.0
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
spec:
  type: LoadBalancer
  selector:
    app: info-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
