apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-service
  labels:
    app: route-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-service
  template:
    metadata:
      labels:
        app: route-service
    spec:
      containers:
        - name: route-service
          image: yangjoanne216/route-service:1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: route-service
spec:
  type: LoadBalancer
  selector:
    app: route-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http