apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
  labels:
    app: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: yangjoanne216/trip-service:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  type: LoadBalancer
  selector:
    app: trip-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
